### ISSUE TITLE
Request for new release and approved status

### ISSUE THREAD

**Issue by tuxmea** [markt-de/puppet-proftpd#33]
Can you please:

- [x] fix #31
- [x] migrate to pdk
- [x] provide a new release on forge
- [ ] request approval status at puppet

We recommend your module in favor of example42-proftpd module.

**Comment by fraenki** [comment]
Thanks for the suggestion. I was considering this some years ago, but things have changed. We'll continue to maintain this module under the markt.de umbrella. :)
