### ISSUE TITLE
Management of the ftpasswd file via concat and as file resource fails

### ISSUE THREAD

**Issue by saz** [markt-de/puppet-proftpd#48]
I've been running into an issue with a missing `ftpd.passwd` file. After some research, I stumbled upon https://github.com/puppetlabs/puppetlabs-concat/issues/806 which seems to be the issue here.

I'll send a PR, which will use a file resource only if `$manage_ftpasswd_file` is set to `false`.

**Comment by saz** [comment]
@fraenki I hope it's fine to also simplify the `concat` part a bit within this PR. If not, please let me know and I'll split it

**Comment by fraenki** [comment]
Thanks for taking care of this.
